FROM grafana/grafana-enterprise:latest

ADD ./config/Datasource.yml /etc/grafana/provisioning/datasources/
ADD ./config/Dashboard.yml /etc/grafana/provisioning/dashboards/
ADD ./config/aegis-gateway-analytics.json /etc/grafana/provisioning/dash/aegis-gateway-analytics.json