services:
    clickhouse:
        build:
            context: .
            dockerfile: Dockerfile-CH
        user: '101:101'
        restart: unless-stopped
        ports:
            - '3218:8123/tcp'
            - '1238:9000/tcp'
        volumes:
            - ${PWD}/volumes/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
            - ${PWD}/volumes/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
        environment:
            - CLICKHOUSE_USER=clickhouse
            - CLICKHOUSE_PASSWORD=password123
    grafana:
        build:
            context: .
            dockerfile: Dockerfile-GF
        restart: unless-stopped
        ports:
            - '5687:3000/tcp'
        volumes:
            - /path/to/ssl/fullchain.pem:/etc/certs/fullchain.pem
            - /path/to/ssl/privkey.pem:/etc/certs/privkey.pem
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=<YOUR_PASSWORD>
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
            - GF_SECURITY_ALLOW_EMBEDDING=true
            # - GF_SERVER_CERT_KEY=/etc/certs/privkey.pem
            # - GF_SERVER_CERT_FILE=/etc/certs/fullchain.pem
            - GF_SERVER_PROTOCOL=https
        depends_on:
            - clickhouse
