FROM grafana/grafana-enterprise:latest

ADD ./config/Datasource.yaml /etc/grafana/provisioning/datasources/main.yaml
ADD ./config/Dashboard.yaml /etc/grafana/provisioning/dashboards/main.yaml
ADD ./config/dashboards /var/lib/grafana/dashboards